import LayoutHeader from '../components/Layout/Header'

import '../styles/reset.scss'

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <div className="index-layout">
          <LayoutHeader />

          <main className="index-container">{children}</main>
        </div>
      </body>
    </html>
  )
}
