import LayoutHeader from '#/components/Layout/Header'
import LayoutFooter from '#/components/Layout/Footer'

import '#/styles/reset.scss'
import '#/styles/style.scss'

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <div className="index-layout">
          <LayoutHeader />

          <main className="layout-container">{children}</main>

          <LayoutFooter />
        </div>
      </body>
    </html>
  )
}
