import Head from 'next/head'
import Link from 'next/link'

async function getData() {
  const res = await fetch('http://localhost:3000/api/hello')
  return res.json()
}

export default async function Home() {
  const data = await getData()

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        Home : {data.name}
        <br />
        <Link href="/about">about</Link>
      </div>
    </div>
  )
}
